CREATE DATABASE escola;

USE escola ;

CREATE TABLE tbl_aluno(
codigo_aluno INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(500) NOT NULL,
sobrenome VARCHAR(500) NOT NULL,
rg VARCHAR(20) NOT NULL,
cpf VARCHAR(20) NOT NULL,
email VARCHAR(100) NOT NULL,
telefone VARCHAR(20) NOT NULL,
celular VARCHAR(20) NOT NULL);